import { v4 as uuid } from "uuid";


export const products = [
  {
    _id: uuid(),
    itemName: "Bread",
     imgUrl: "https://www.kindpng.com/picc/m/92-924604_sliced-bread-hd-png-download.png",
    price: "50",
    category: "Bakery",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Eggs",
    imgUrl: "https://c1.wallpaperflare.com/preview/93/55/639/eggs-white-basket-breakfast.jpg",
    price: "60",
    category: "bakery",
    rating:2,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "dal",
    imgUrl: "https://thumbs.dreamstime.com/b/dried-chana-dal-beans-wooden-spoon-chana-dal-213878023.jpg",
    price: "185",
    category: "pulse",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Carrot",
    imgUrl: "https://images.pexels.com/photos/65174/pexels-photo-65174.jpeg?cs=srgb&dl=pexels-mali-maeder-65174.jpg&fm=jpg",
    price: "35",
    category: "vegetable",
    rating:2,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Potato",
    imgUrl:"https://wallpapercave.com/wp/wp1885850.jpg",
    price: "20",
    category: "vegetable",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Dhaniya",
    imgUrl:"https://images.unsplash.com/photo-1588879460618-9249e7d947d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y29yaWFuZGVyJTIwbGVhdmVzfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
    price: "20",
    category: "vegetable",
    rating:3,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Palak",
    imgUrl:"https://m.media-amazon.com/images/I/81wkaMZmdbL._SL1500_.jpg",
    price: "15",
    category: "vegetable",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Onion",
    imgUrl:"https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8b25pb258ZW58MHx8MHx8&w=1000&q=80",
    price: "50",
    category: "vegetable",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Tomato",
    imgUrl:"https://i.pinimg.com/originals/e5/02/25/e50225e890395e3b09617906e441fb9a.jpg",
    price: "17",
    category: "vegetable",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Cookie",
    imgUrl:"https://images.unsplash.com/photo-1557089706-68d02dbda277?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGJpc2N1aXR8ZW58MHx8MHx8&w=1000&q=80",
    price: "90",
    category: "bakery",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Cake",
    imgUrl:"https://thumbs.dreamstime.com/b/birthday-cake-chocolate-candles-70779992.jpg",
    price: "500",
    category: "bakery",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Milk",
    imgUrl:"https://media.istockphoto.com/photos/pouring-milk-in-the-glass-on-the-background-of-nature-picture-id535489242?b=1&k=20&m=535489242&s=170667a&w=0&h=0W-juXEHTzEumP4WuJTac0020nc1Zc7LCncRdEJMXgk=",
    price: "32",
    category: "bakery",
    rating:2,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Pancake",
    imgUrl:"https://media.istockphoto.com/photos/pancakes-with-berries-and-maple-syrup-picture-id161170090?b=1&k=20&m=161170090&s=170667a&w=0&h=pgtnBdQKLvZz7WOmBcZhY_EXDGeATOS2jc_FJF9GbnE=",
    price: "250",
    category: "bakery",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "coke",
    imgUrl:"https://images.unsplash.com/photo-1554866585-cd94860890b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y29jYWNvbGF8ZW58MHx8MHx8&w=1000&q=80",
    price: "22",
    category: "juice",
    rating:3,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Fanta",
    imgUrl:"https://images.unsplash.com/photo-1624517452488-04869289c4ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZmFudGF8ZW58MHx8MHx8&w=1000&q=80",
    price: "22",
    category: "juice",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Lizol",
    imgUrl:"https://5.imimg.com/data5/RW/CA/MY-21257986/lizol-500x500.jpg",
    price: "95",
    category: "Home",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Hajmola",
    imgUrl:"http://cdn.shopify.com/s/files/1/0415/0460/4309/products/1_df75dd99-f443-447a-a85f-20d323212f4b_600x600.jpg?v=1598636332",
    price: "35",
    category: "medicine",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Pudin Hara",
    imgUrl:"https://www.netmeds.com/images/product-v1/600x600/15917/dabur_pudin_hara_pearls_capsule_10_s_0.jpg",
    price: "19",
    category: "medicine",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Dolo 650",
    imgUrl:"https://static.oxinis.com/healthmug/image/product/108652-4-1000.jpg",
    price: "45",
    category: "medicine",
    rating:2,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Eno",
    imgUrl:"https://image.shutterstock.com/image-photo/new-delhi-india-20-november-260nw-1858255309.jpg",
    price: "6",
    category: "medicine",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Rice",
    imgUrl:"https://thumbs.dreamstime.com/b/rice-grain-22274736.jpg",
    price: "112",
    category: "pulse",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Atta",
    imgUrl:"http://www.bmbtfoods.com/assets/img/best-atta-brand.jpg",
    price: "45",
    category: "pulse",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Honey",
    imgUrl:"https://images.unsplash.com/photo-1587049352851-8d4e89133924?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8aG9uZXl8ZW58MHx8MHx8&w=1000&q=80",
    price: "80",
    category: "healthy",
    rating:2,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Ghee",
    imgUrl:"https://thumbs.dreamstime.com/b/ghee-clarified-butter-close-up-wooden-bowl-silver-spoon-selective-focus-indian-desi-ghee-pure-ghee-served-101142931.jpg",
    price: "450",
    category: "healthy",
    rating:3,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Gulab jamun",
    imgUrl:"https://www.teahub.io/photos/full/187-1874801_indian-sweet-balls-called-gulab-jamun-hd-image.jpg",
    price: "80",
    category: "sweets",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Barfi",
    imgUrl:"https://image.shutterstock.com/image-photo/kaju-katli2-260nw-128021285.jpg",
    price: "1000",
    category: "sweets",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Ladoo",
    imgUrl:"https://c1.wallpaperflare.com/preview/866/519/654/sweets-round-patiala-punjab.jpg",
    price: "250",
    category: "sweets",
    rating:2,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Son Papdi",
    imgUrl:"https://thumbs.dreamstime.com/b/homemade-traditional-indian-sweet-snack-soan-papdi-vegan-diet-snack-soan-papdi-famous-north-indian-sweet-131633504.jpg",
    price: "95",
    category: "sweets",
    rating:3,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Colgate",
    imgUrl:"https://m.media-amazon.com/images/I/61wcVTAY4vL._SX425_.jpg",
    price: "105",
    category: "Home",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Bhujia",
    imgUrl:"https://www.haldirams.com/media/catalog/product/cache/e0f2a41d8b7a0fa5626b9201a6cf0006/a/l/aloo_bhujia_1_2.jpg",
    price: "20",
    category: "snacks",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Corn Flakes",
    imgUrl:"https://image.shutterstock.com/image-photo/healthy-corn-flakes-milk-breakfast-260nw-1021375678.jpg",
    price: "95",
    category: "breakfast",
    rating:1,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Noodles",
    imgUrl:"https://cdn.wallpapersafari.com/55/27/zDXIob.jpg",
    price: "65",
    category: "breakfast",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Masoor dal",
    imgUrl:"https://thumbs.dreamstime.com/b/red-masoor-dal-small-red-coloured-lentils-used-indian-food-38458273.jpg",
    price: "165",
    category: "pulse",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Daliya",
    imgUrl:"https://thumbs.dreamstime.com/b/raw-broken-wheat-daliya-dalia-selective-focus-gehu-also-known-as-cracked-served-bowl-spoon-healthy-indian-food-189288643.jpg",
    price: "30",
    category: "healthy",
    rating:4,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Oats",
    imgUrl:"https://ak.picdn.net/shutterstock/videos/1035539096/thumb/12.jpg?ip=x480",
    price: "100",
    category: "healthy",
    rating:3,
    isWishlisted: false,
    isAddedToCart: false,
  },
  {
    _id: uuid(),
    itemName: "Oreo",
    imgUrl:"https://media.istockphoto.com/photos/sandwich-cocoa-cookie-with-crema-inside-picture-id687935710?b=1&k=20&m=687935710&s=170667a&w=0&h=iVR6wuexUtVeyX_xgIy5GSlDwp2XJzAbb8Wo-OGUpIE=",
    price: "60",
    category: "snacks",
    rating:5,
    isWishlisted: false,
    isAddedToCart: false,
  },
  
];
